### PR TITLE
Add GRADLE_DIST argument

### PR DESCRIPTION
**Pull request by owjsub**

### CODE REVIEW

**Comment by thyrlian** [comment]
HI @owjsub, thanks for your PR 👍 

Out of curiosity, when would someone need other gradle distribution than `bin`?  `all` is too big, and we don't want to compile `src` ourselves.  Especially this Docker image would be primarily used as CI build environment.

**Comment by owjsub** [comment]
Perhaps `all` could be useful if this Docker image was used as a development environment.

**Comment by thyrlian** [comment]
For my usual development purpose, I never have the need to use `all`.  Could you share any concrete example of using `all`?  Thanks.

**Comment by owjsub** [comment]
It can be useful for code completion in `build.gradle` and the ability to navigate to Gradle source code.

**Comment by thyrlian** [comment]
Yes, if you want to debug gradle source code, you'll need that.

**Pull request merged**
